name: "PR Labeler"
description: "Labels a PR"

inputs:
  configuration-path:
    description: "Path to the configuration file"
    required: false
    default: ".github/labeler.yml"
  repository:
    description: "Path to a repository to reference external configuration file"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout external repository
      if: ${{ inputs.repository != '' }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: "${{ inputs.repository }}"
        persist-credentials: false
    - name: Label PR
      uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
      with:
        configuration-path: ${{ inputs.configuration-path }}
