name: "Trivy Dependency Scan"
description: "Run a Trivy filesystem scan of the repository"

inputs:
  trivyignore-files:
    description: "Path(s) to .trivyignore file(s) to ignore known CVEs (comma- or newline-separated)"
    required: false
    default: ".trivyignore"
  timeout:
    description: "timeout for trivy scan"
    required: false
    default: 15m0s

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0 # Required for vitepress lastUpdated
        persist-credentials: false
    - name: Run Trivy vulnerability scanner in repository mode
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      with:
        scan-type: "fs"
        scan-ref: "."
        format: "json"
        exit-code: "1"
        timeout: "${{ inputs.timeout }}"
        trivyignores: ${{ inputs.trivyignore-files }}
        output: trivy-report.json
    - name: convert
      if: ${{ always() && hashFiles('trivy-report.json') != '' }}
      shell: bash
      run: |
        trivy convert --format table --output trivy-results.txt  trivy-report.json
        cat trivy-results.txt
        trivy convert --format sarif --output trivy-results.sarif  trivy-report.json

    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: trivy-report
        path: trivy-report.json
        retention-days: 7

    - name: Upload Trivy scan results to GitHub Security tab
      if: ${{ always() && hashFiles('trivy-results.sarif') != '' }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: "trivy-results.sarif"
