name: "Trivy Dependency Scan"
description: "Run a Trivy filesystem scan of the repository"

inputs:
  trivyignore-files:
    description: "Path(s) to .trivyignore file(s) to ignore known CVEs (comma- or newline-separated)"
    required: false
    default: ".trivyignore"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Run Trivy vulnerability scanner in repository mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        scan-type: "fs"
        scan-ref: "."
        format: "table"
        exit-code: "1"
        trivyignores: ${{ inputs.trivyignore-files }}
