name: "Trivy Dependency Scan"
description: "Run a Trivy filesystem scan of the repository"

inputs:
  trivyignore-files:
    description: "Path(s) to .trivyignore file(s) to ignore known CVEs (comma- or newline-separated)"
    required: false
    default: ".trivyignore"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0 # Required for vitepress lastUpdated
        persist-credentials: false
    - name: Run Trivy vulnerability scanner in repository mode
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      with:
        scan-type: "fs"
        scan-ref: "."
        format: "json"
        exit-code: "1"
        trivyignores: ${{ inputs.trivyignore-files }}
        output: trivy-report.json
    - name: abc
      if: always()
      shell: bash
      run: |
        trivy convert --format table --output trivy-results.txt  trivy-report.json
        cat trivy-results.txt

    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      if: always()
      with:
        name: trivy-report
        path: trivy-report.json
        retention-days: 7
