name: "Trivy Dependency Scan"
description: "Run a Trivy filesystem scan of the repository"

inputs:
  trivyignore-files:
    description: "Path(s) to .trivyignore file(s) to ignore known CVEs (comma- or newline-separated)"
    required: false
    default: ".trivyignore"
  timeout:
    description: "timeout for trivy scan"
    required: false
    default: 15m0s
  path:
    description: "Path to scan with Trivy"
    required: false
    default: "."
  scan-type:
    description: "scan type, e.g. fs or sbom"
    required: false
    default: "fs"
    
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if:  inputs.scan-type  == 'fs'
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0 # Required for vitepress lastUpdated
        persist-credentials: false
    - name: Run Trivy vulnerability scanner in repository mode
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      env:
        TRIVY_INCLUDE_DEV_DEPS: "true"
      with:
        scan-type: "${{ inputs.scan-type }}"
        scan-ref: "${{ inputs.path }}"
        format: "json"
        exit-code: "1"
        timeout: "${{ inputs.timeout }}"
        trivyignores: ${{ inputs.trivyignore-files }}
        output: trivy-report.json
    - name: convert
      if: ${{ always() && hashFiles('trivy-report.json') != '' }}
      shell: bash
      run: |
        trivy convert --format table --output trivy-results.txt  trivy-report.json
        cat trivy-results.txt
        trivy convert --format sarif --output trivy-results.sarif  trivy-report.json

    - name: Upload Vulnerability Scan Results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: trivy-report
        path: trivy-report.json
        retention-days: 7

    - name: Upload Trivy scan results to GitHub Security tab
      if: ${{ always() && hashFiles('trivy-results.sarif') != '' }}
      uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
      with:
        sarif_file: "trivy-results.sarif"
