name: "Build Docker image"
description: "Builds and pushes a Docker image"

inputs:
  registry:
    description: "Image registry to push image to"
    required: true
    default: ghcr.io
  registry-username:
    description: "Username to authenticate against image registry"
    required: true
  registry-password:
    description: "Password to authenticate against image registry"
    required: true
  image-tags:
    description: "Tags to tag image with"
    required: false
    default: |
      type=raw,value=latest
  image-labels:
    description: "Labels to add to image"
    required: false
    default: |
      org.opencontainers.image.description=See ${{ github.server_url }}/${{ github.repository }}
  path:
    description: "Path to the build context directory (containing the Dockerfile)"
    required: true
  image-name:
    description: "Name to give the image"
    required: true
  artifact-name:
    description: "Name of artifact to download "
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Download a single artifact
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: ${{ inputs.artifact-name }}
    - name: Login to registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
      with:
        images: "${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}"
        tags: ${{inputs.image-tags}}
        labels: ${{inputs.image-labels}}

    - name: Build and push image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ./${{ inputs.path }} # zizmor: ignore[template-injection]
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        github-token: ${{ github.token }}
