name: "Build Docker image"
description: "Builds and pushes a Docker image"

inputs:
  registry:
    description: "Image registry to push image to"
    required: true
    default: ghcr.io
  registry-username:
    description: "Username to authenticate against image registry"
    required: true
  registry-password:
    description: "Password to authenticate against image registry"
    required: true
  image-tags:
    description: "Tags to tag image with"
    required: false
    default: |
      type=raw,value=latest
  image-labels:
    description: "Labels to add to image"
    required: false
    default: |
      org.opencontainers.image.description=See ${{ github.server_url }}/${{ github.repository }}
  path:
    description: "Path to the Dockerfile to build image from"
    required: true
  image-name:
    description: "Name to give the image"
    required: true
  artifact-name:
    description: "Name of artifact to download "
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Download a single artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{ inputs.artifact-name }}
    - name: Login to registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
      with:
        images: "${{ inputs.registry }}/${{ github.repository }}/${{ inputs.image-name }}"
        tags: ${{inputs.image-tags}}
        labels: ${{inputs.image-labels}}
    - name: Build and push image
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ./${{ inputs.path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
