name: "Require PR checklist"
description: "Fails if a PR checklist is required but doesn't exist"

inputs:
  fail-missing:
    description: "Whether the action should fail if the PR contains no checklist"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Configure checklist requirement
      if: ${{ github.event.pull_request.draft == false && github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'renovate[bot]' }}
      uses: mheap/require-checklist-action@46d2ca1a0f90144bd081fd13a80b1dc581759365 # v2.5.0
      with:
        requireChecklist: ${{ inputs.fail-missing }}
        skipDescriptionRegex: .*\(optional\).*
