name: "Validate docker stack"
description: "Validates a docker compose stack using its defined health checks"

inputs:
  max-retries:
    description: "Maximum number of retry attempts"
    required: false
    default: "10"
  retry-interval:
    description: "Interval between retries in seconds"
    required: false
    default: "10"
  compose-file-path:
    description: "Path to the docker compose file"
    required: false
    default: "./"
  compose-file-name:
    description: "Name of the docker compose file"
    required: false
    default: "docker-compose.yml"
  skip-no-healthcheck:
    description: "Skip checking containers without health checks"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false
    - name: Run Docker Compose stack
      working-directory: ${{ inputs.compose-file-path }}
      shell: bash
      run: docker compose -f ${{ inputs.compose-file-name }} up -d
    - name: Run Docker Compose healthcheck
      working-directory: ${{ inputs.compose-file-path }}
      shell: bash
      env:
        MAX_RETRIES: ${{ inputs.max-retries }}
        RETRY_INTERVAL: ${{ inputs.retry-interval }}
        COMPOSE_FILE_NAME: ${{ inputs.compose-file-name }}
        SKIP_NO_HEALTHCHECK: ${{ inputs.skip-no-healthcheck }}
      run: ${{ github.action_path }}/run.sh
