name: "Validate docker stack"
description: "Validates a docker compose stack using its defined health checks"

inputs:
  max-retries:
    description: "Maximum number of retry attempts"
    required: false
    default: "10"
  retry-interval:
    description: "Interval between retries in seconds"
    required: false
    default: "10"
  compose-file-path:
    description: "Path to the docker compose file"
    required: false
    default: "./"
  compose-file-name:
    description: "Name of the docker compose file"
    required: false
    default: "docker-compose.yml"
  skip-exited:
    description: "Skip checking exited containers (useful for init containers)"
    required: false
    default: "false"
  skip-no-healthcheck:
    description: "Skip checking containers without health checks"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Start Docker Compose services
      env:
        COMPOSE_FILE_PATH: ${{ inputs.compose-file-path }}
      run: |
        cd $COMPOSE_FILE_PATH
        docker compose up -d
      shell: bash
    - name: Run health check
      uses: jaracogmbh/docker-compose-health-check-action@973fbdccf7c8e396b652d3501984c8e530a9fa80 # v1.0.0
      with:
        max-retries: ${{ inputs.max-retries }}
        retry-interval: ${{ inputs.retry-interval }}
        compose-file: ${{ inputs.compose-file-path }}${{ inputs.compose-file-name }}
        skip-exited: ${{ inputs.skip-exited }}
        skip-no-healthcheck: ${{ inputs.skip-no-healthcheck }}
