name: "Maven build"
description: "Executes a Maven build and uploads the generated artifact to Maven Central"

inputs:
  java-version:
    description: "Java version to use for the build"
    required: false
    default: "21"
  app-path:
    description: "Path to the project’s pom.xml file"
    required: true

outputs:
  artifact-name:
    description: "Name of the artifact upload"
    value: ${{steps.artifact-name.outputs.artifact-name}}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"
        cache: "maven"
        cache-dependency-path: "./${{inputs.app-path}}/pom.xml"
    - name: Build with Maven
      env:
        APP_PATH: ${{inputs.app-path}}
      run: mvn --update-snapshots -f ./$APP_PATH/pom.xml install
      shell: bash
    - id: artifact-name
      name: Set output variable $GITHUB_OUTPUT
      run: echo "artifact-name=${{hashFiles(format('./{0}/pom.xml', inputs.app-path))}}" >> "$GITHUB_OUTPUT"
      shell: bash
    - id: upload-artifact
      name: Upload artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: ${{steps.artifact-name.outputs.artifact-name}}
        path: "**/target"
        retention-days: 5
