name: "Deploy docs"

inputs:
  artifact-name:
    description: "The name of the artifact to deploy"
    required: false
    default: "github-pages"
  deploy-branch:
    description: "Branch to deploy documentation from"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      if: (github.ref_name == inputs.deploy-branch)
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
      with:
        artifact_name: ${{ inputs.artifact-name }}
