name: "Deploy docs"
description: "Deploy docs to GitHub Pages"

inputs:
  artifact_name:
    description: "The name of the artifact to deploy"
    required: false
    default: "github-pages"
  deploy-branch:
    description: "Branch to deploy documentation from"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      if: (github.ref_name == inputs.deploy-branch)
      uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
      with:
        artifact_name: ${{ inputs.artifact_name }}
