name: "Execute paths-filter"
description: "Execute paths-filter with input of filters"

inputs:
  filters:
    description: "Defines filters applied to detected changed files"
    required: false
    default: |
      java:
        - '**/*.java'
      javascript-typescript-vue:
        - '**/*.js'
        - '**/*.cjs'
        - '**/*.mjs'
        - '**/*.ts'
        - '**/*.cts'
        - '**/*.mts'
        - '**/*.vue'
      python:
        - '**/*.py'

outputs:
  java:
    description: "Name of the java artifact upload"
    value: ${{ steps.filter.outputs.java }}
  javascript-typescript-vue:
    description: "Name of the vue artifact upload"
    value: ${{ steps.filter.outputs.javascript-typescript-vue }}
  python:
    description: "Name of the python artifact upload"
    value: ${{ steps.filter.outputs.python }}

runs:
  using: "composite"
  steps:
    - name: Check changed files and directories
      id: filter
      uses: dorny/paths-filter@d1c1ffe0248fe513906c8e24db8ea791d46f8590 # v3.0.3
      with:
        filters: ${{ inputs.filters }}
