name: "Execute paths-filter"
description: "Execute paths-filter with input of filters"

inputs:
  filters:
    description: "Defines filters applied to detected changed files"
    required: false
    default: |
      java:
        - '**/*.java'
      javascript-typescript-vue:
        - '**/*.js'
        - '**/*.cjs'
        - '**/*.mjs'
        - '**/*.ts'
        - '**/*.cts'
        - '**/*.mts'
        - '**/*.vue'
      python:
        - '**/*.py'

outputs:
  java:
    description: "Name of the java artifact upload"
    value: ${{ steps.filter.outputs.java }}
  javascript-typescript-vue:
    description: "Name of the vue artifact upload"
    value: ${{ steps.filter.outputs.javascript-typescript-vue }}
  python:
    description: "Name of the python artifact upload"
    value: ${{ steps.filter.outputs.python }}
  changes:
    description: "JSON array of filter names that have matched changes"
    value: ${{ steps.filter.outputs.changes }}

runs:
  using: "composite"
  steps:
    - name: Check changed files and directories
      id: filter
      uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
      with:
        filters: ${{ inputs.filters }}
