name: "Npm release"
description: "Creates a new npm release pull request"

inputs:
  node-version:
    description: "Node version"
    required: false
    default: "22"
  app-path:
    description: "Path to package.json file"
    required: true
  releaseVersion:
    description: "Select version increment type (follows Semantic Versioning)"
    required: true
  npm-token:
    description: "npm token for release"
    required: true
  use-pr:
    description: "Use PR for version bump instead of direct push"
    default: "false"

outputs:
  ARTIFACT_VERSION:
    description: "Version number of the artifact upload"
    value: ${{steps.node-release.outputs.VERSION}}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: "${{ inputs.node-version }}"
        registry-url: "https://registry.npmjs.org"
        cache: "npm"
        cache-dependency-path: "./${{inputs.app-path}}/package-lock.json"
    - id: node-release
      name: Bump version and create git tag
      working-directory: ./${{inputs.app-path}}
      shell: bash
      run: |
        NEW_VERSION=$(npm version ${{inputs.releaseVersion}}) || exit 1
        echo "VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add package.json package-lock.json
        git commit -m "chore(${{ inputs.app-path }}): bump version to ${NEW_VERSION}" || exit 1

    - name: Push changes
      if: ${{ inputs.use-pr != 'true' }}
      shell: bash
      run: git push || exit 1

    - name: Push changes to release branch and create pull request
      if: ${{ inputs.use-pr == 'true' }}
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
      with:
        title: "chore(${{ inputs.app-path }}): bump release version to ${{ env.NEW_VERSION }}"
        branch: "release-${{ inputs.app-path }}-${{ env.NEW_VERSION }}"
        base: "${{ github.ref_name }}"
        body: "This PR is auto-generated"
        assignees: "${{ github.actor }}"
