name: Npm release

inputs:
  node-version:
    required: false
    default: "22.11.0"
    type: string
    description: "Node version"
  app-path:
    required: true
    type: string
    description: "Path to package.json file"
  release-version:
    type: choice
    description: "Select version increment type (follows Semantic Versioning)"
    required: true
    options:
      - patch
      - minor
      - major
  npm-token:
    type: string
    required: true
    description: "Npm token for release"
outputs:
  ARTIFACT_VERSION:
    description: "Version of the artifact upload"
    value: ${{steps.node-release.outputs.VERSION}}
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: "${{ inputs.node-version }}"
        registry-url: "https://registry.npmjs.org"
        cache: "npm"
        cache-dependency-path: "./${{inputs.app-path}}/package-lock.json"
    - id: node-release
      name: Bump version and create git tag
      working-directory: ./${{inputs.app-path}}
      run: |
        NEW_VERSION=$(npm version ${{inputs.release-version}}) || exit 1
        echo "VERSION=$NEW_VERSION" >> "$GITHUB_OUTPUT"
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add package.json package-lock.json
        git commit -m "Bump version to ${NEW_VERSION}" || exit 1
        git tag "${NEW_VERSION}" || exit 1
        git push && git push --tags || exit 1
      shell: bash
