name: "Maven release"
description: "Creates a Maven release pull request"

inputs:
  java-version:
    description: "Java version to use for the build. If not set extract the version from the `pom.xml` on the attribute `java.version`."
    required: false
  app-path:
    description: "Path to the project’s pom.xml file"
    required: true
  release-method:
    description: "Release-Methode = patch, minor oder major"
    required: false
    default: "patch"
  releaseVersion:
    description: "Version to be released. The value is calculated if release-method is set"
    required: false
    default: ""
  developmentVersion:
    description: "Deprecated: Next version with snapshot"
    required: false
    default: ""
  skipDeployment:
    description: "Skip deployment to Maven Central"
    default: "true"
  use-pr:
    description: "Use PR for version bump instead of direct push"
    default: "false"
  mavenDArgsInput:
    description: "Additional maven arguments"
    default: ""
    required: false
  GPG_PRIVATE_KEY:
    description: "GPG private key to import"
    required: false
  SIGN_KEY_PASS:
    description: "Environment variable name for the GPG private key passphrase"
    required: false
  CENTRAL_USERNAME:
    description: "Environment variable name for the username for authentication to Maven Central"
    required: false
  CENTRAL_PASSWORD:
    description: "Environment variable name for password or token for authentication to Maven Central"
    required: false

outputs:
  MVN_ARTIFACT_ID:
    description: "Artifact name from pom"
    value: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
  artifact-name:
    description: "Name of the artifact upload"
    value: ${{steps.artifact-name.outputs.artifact-name}}
  release-version:
    description: "calculated release version"
    value: ${{steps.maven-release-step.outputs.FINAL_RELEASE_VERSION }}

runs:
  using: "composite"
  steps:
    # Checkout source code, set up Java, etc. Then...
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: true
    - name: Extract Java Version from pom.xml
      id: get-java-version
      shell: bash
      env:
        APP_PATH: ${{inputs.app-path}}
        JAVA_VERSION: ${{ inputs.java-version }}
      run: |
        # Check if the input java-version is empty
        if [ -z "$JAVA_VERSION" ]; then
            # Extract from pom.xml if input is empty
            JAVA_VERSION=$(grep -oP '(?<=<(java.version)>)[^<]+' "$APP_PATH/pom.xml" | head -n 1)
        fi

        # Fail the build if no version could be determined at all
        if [ -z "$JAVA_VERSION" ]; then
            echo "Error: Java version could not be determined!"
            exit 1
        fi

        # Save the version to step outputs
        echo "java-version=$JAVA_VERSION" >> "$GITHUB_OUTPUT"
    - name: Set up JDK
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
      with:
        java-version: ${{ steps.get-java-version.outputs.java-version }}
        distribution: "temurin"
        cache: "maven"
        cache-dependency-path: "./${{ inputs.app-path}}/pom.xml"
        server-id: "central"
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ inputs.GPG_PRIVATE_KEY }}
        gpg-passphrase: SIGN_KEY_PASS
    - name: Maven release step
      id: maven-release-step
      shell: bash
      env:
        SIGN_KEY_PASS: ${{ inputs.SIGN_KEY_PASS }}
        CENTRAL_USERNAME: ${{ inputs.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ inputs.CENTRAL_PASSWORD }}
        SKIP_DEPLOYMENT: ${{ inputs.skipDeployment }}
        USE_PR: ${{ inputs.use-pr != 'true' }}
        APP_PATH: ${{inputs.app-path}}
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
        RELEASE_METHOD: ${{ inputs.release-method }}
        DEVELOPMENT_VERSION: ${{ inputs.developmentVersion }}
        DARGUMENTS: ${{ inputs.mavenDArgsInput }}
      run: |
        # configure git
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        # get maven artifact id and provide as output
        MVN_ARTIFACT_ID=$(mvn -f ./$APP_PATH/pom.xml org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -DforceStdout | tee /dev/stderr | tail -n 1)
        echo $MVN_ARTIFACT_ID
        echo "MVN_ARTIFACT_ID=$MVN_ARTIFACT_ID" >> $GITHUB_OUTPUT

        MVN_VERSION=$(mvn -f $APP_PATH/pom.xml $MAVEN_CLI_OPTS org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout )

        if [ -z $RELEASE_VERSION ]; then RELEASE="${MVN_VERSION/-SNAPSHOT/""}"; else RELEASE=$RELEASE_VERSION; fi
        echo $RELEASE
        if [[ "$RELEASE_METHOD" != "major" && "$RELEASE_METHOD" != "minor"  && "$RELEASE_METHOD" != "patch" ]]; then
          echo "wrong release method"
          exit 1
        fi
        if [ "$RELEASE_METHOD" == "major" ]; then MAJOR=$(( $(echo $RELEASE | awk -F. '{print $1}') + 1 )); else MAJOR=$(echo $RELEASE | awk -F. '{print $1}'); fi
        if [ "$RELEASE_METHOD" == "major" ]; then MINOR=0; elif [ "$RELEASE_METHOD" == "minor" ]; then MINOR=$(( $(echo $RELEASE | awk -F. '{print $2}' ) + 1 )); else MINOR=$(echo $RELEASE | awk -F. '{print $2}' ); fi
        if [ "$RELEASE_METHOD" != "major" ] && [ "$RELEASE_METHOD" != "minor" ]; then PATCH=$(( $(echo $RELEASE | awk -F. '{print $3}') + 1 )); else PATCH=0; fi
        if [[ -z "$DEVELOPMENT_VERSION" ]]; then
           DEVELOPMENT_VERSION=$(echo $MAJOR.$MINOR.$PATCH-SNAPSHOT)
        fi
        echo FINAL_RELEASE_VERSION=$RELEASE >> $GITHUB_OUTPUT
        echo "DEVELOPMENT_VERSION=$DEVELOPMENT_VERSION" >> $GITHUB_OUTPUT

        # prepare the maven arguments
        MAVEN_ARGS="-DpushChanges=$USE_PR -DremoteTagging=false -DlocalCheckout=true"
        # set maven deploy skip if skipDeployment is true
        if [[ "$SKIP_DEPLOYMENT" == "true" ]]; then
          DARGUMENTS="$DARGUMENTS -Dmaven.deploy.skip=true"
        fi

        # run maven release
        mvn release:prepare release:perform -f ./$APP_PATH/pom.xml -B \
          -DreleaseVersion=$RELEASE -DdevelopmentVersion=$DEVELOPMENT_VERSION  \
          $MAVEN_ARGS \
          -Darguments="$DARGUMENTS"

    - id: artifact-name
      name: Set output variable $GITHUB_OUTPUT
      run: echo "artifact-name=${{hashFiles(format('./{0}/pom.xml', inputs.app-path))}}" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{steps.artifact-name.outputs.artifact-name}}
        path: "**/target"
        retention-days: 5

    - name: Push changes to release branch and create pull request
      if: ${{ inputs.use-pr == 'true' }}
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        title: "chore(${{ inputs.app-path }}): bump release version to ${{ steps.maven-release-step.outputs.DEVELOPMENT_VERSION }}"
        branch: "release-${{ inputs.app-path }}-${{ steps.maven-release-step.outputs.DEVELOPMENT_VERSION }}"
        base: "${{ github.ref_name }}"
        body: "This PR is auto-generated"
        assignees: "${{ github.actor }}"
