name: "Checkout repository"
description: "A wrapper for actions/checkout setting persist-credentials per default to false"
inputs:
  persist-credentials:
    description: "Whether to persist your credentials or not"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository without persisting credentials
      if: ${{ inputs.persist-credentials != 'true' }}
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false
    - name: Checkout repository with persisting credentials
      if: ${{ inputs.persist-credentials == 'true' }}
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: true
