name: "Checkout Code"
description: "A wrapper for actions/checkout with no args"
inputs:
  filters:
    required: false
    default: ""
    type: string
    description: Defines filters applied to detected changed files.
outputs:
  java:
    description: "name of the artifact upload"
    value: ${{ steps.filter.outputs.java }}
  javascript-typescript-vue:
    description: "name of the artifact upload"
    value: ${{ steps.filter.outputs.javascript-typescript-vue }}
  python:
    description: "name of the artifact upload"
    value: ${{ steps.filter.outputs.python }}
# Line 19 in action-templates/actions/action-checkout/action.yml after fix (empty line with no trailing spaces)
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Check changed files and directories
      id: filter
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      with: 
       filters: 
         ${{ inputs.filters  }}
