# https://vitepress.dev/guide/deploy#github-pages
name: "Build docs"
description: "Build docs with VitePress or VuePress"

inputs:
  docs-path:
    description: "Path to VitePress docs project"
    required: false
    default: "./docs"
  node-version:
    description: "Node version"
    required: false
    default: "22"
  build-cmd:
    description: "Build command to run (e.g. for VuePress use: vuepress build)"
    required: false
    default: "build"
  dist-path:
    description: "Output directory that will be uploaded to GitHub Pages"
    required: false
    default: ".vitepress/dist"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        fetch-depth: 0 # Required for vitepress lastUpdated
        persist-credentials: false
    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: "${{ inputs.docs-path }}/package-lock.json"
    - name: Setup Pages
      uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
    - name: Run ci lint build
      shell: bash
      env:
        DOCS_PATH: ${{ inputs.docs-path }}
        BUILD_CMD: ${{ inputs.build-cmd }}
      run: |
        npm --prefix "$DOCS_PATH" ci
        npm --prefix "$DOCS_PATH" run  lint
        npm --prefix "$DOCS_PATH" run "$BUILD_CMD"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: ${{ inputs.docs-path }}/${{ inputs.dist-path }}
