name: "Create GitHub Release"
description: "Creates a GitHub Release of a Maven Artifact"

inputs:
  artifact-name:
    description: "name of the artifact to download"
    required: true
  tag-name:
    description: "Name of a tag (e.g. sps-1.0.0 or myproject-1.0.0)"
    required: true
  artifact-path:
    description: "path to the artifacts (e.g. ./target/*.jar)"
    required: true
  draft:
    description: "if is draft release"
    default: "false"
  prerelease:
    description: "if is prerelease"
    default: "false"
  generate-release-notes:
    description: "if release notes should be generated"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Download a single artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{inputs.artifact-name}}
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
      with:
        tag_name: ${{inputs.tag-name}}
        draft: ${{inputs.draft == 'true'}}
        prerelease: ${{inputs.prerelease == 'true'}}
        generate_release_notes: ${{inputs.generate-release-notes == 'true'}}
        files: |
          ${{inputs.artifact-path}}
