name: "Create GitHub release"
description: "Creates a GitHub release from a downloaded artifact"
inputs:
  artifact-name:
    description: "Name of the artifact to download"
    required: true
  tag-name:
    description: "Name of a tag (e.g. sps-1.0.0 or myproject-1.0.0)"
    required: true
  artifact-path:
    description: "Path to the artifacts (e.g. ./target/*.jar)"
    required: true
  draft:
    description: "Whether it is a draft release or not"
    default: "false"
  prerelease:
    description: "Whether it is a prerelease or not"
    default: "false"
  generate-release-notes:
    description: "Generate release notes"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Download a single artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ${{inputs.artifact-name}}
    - name: Create GitHub release
      id: create_release
      uses: softprops/action-gh-release@62c96d0c4e8a889135c1f3a25910db8dbe0e85f7 # v2.3.4
      with:
        tag_name: ${{inputs.tag-name}}
        draft: ${{inputs.draft == 'true'}}
        prerelease: ${{inputs.prerelease == 'true'}}
        generate_release_notes: ${{inputs.generate-release-notes == 'true'}}
        files: |
          ${{inputs.artifact-path}}
