name: Create GitHub Release
description: "Creates a GitHub Release of a Maven Artifact"
inputs:
  artifact-name:
    required: true
    type: string
    description: "name of the artifact to download"
  tag-name:
    required: true
    type: string
    description: "Name of a tag (e.g. sps-1.0.0 or myproject-1.0.0)"
  artifact-path:
    required: true
    type: string
    description: "path to the artifacts (e.g. ./target/*.jar)"
runs:
  using: "composite"
  steps:
    - name: Download a single artifact
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: ${{inputs.artifact-name}}
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
      with:
        tag_name: ${{inputs.tag-name}}
        draft: false
        prerelease: false
        generate_release_notes: false
        files: |
          ${{inputs.artifact-path}}
