name: "Dependency review"

inputs:
  allow-dependencies-licenses:
    description: "Contains a comma separated string of packages that will be excluded from license checks"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Dependency review
      uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a # v4.8.1
      with:
        config-file: it-at-m/.github/workflow-configs/dependency_review.yaml@main
        allow-dependencies-licenses: ${{ inputs.allow-dependencies-licenses }}
