name: dependency-review
inputs:
  allow-dependencies-licenses:
    required: false
    default: ""
    type: string
    description: Contains a comma separated string of packages that will be excluded from license checks.
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Dependency Review
      uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
      with:
        config-file: it-at-m/.github/workflow-configs/dependency_review.yaml@main
        allow-dependencies-licenses: ${{ inputs.allow-dependencies-licenses }}
