name: "Dependency review"

inputs:
  allow-dependencies-licenses:
    description: "Contains a comma separated string of packages that will be excluded from license checks"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Dependency review
      uses: actions/dependency-review-action@bc41886e18ea39df68b1b1245f4184881938e050 # v4.7.2
      with:
        config-file: it-at-m/.github/workflow-configs/dependency_review.yaml@main
        allow-dependencies-licenses: ${{ inputs.allow-dependencies-licenses }}
