name: "Lint actions"
description: "Lints GitHub workflow files using actionlint"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false
    - uses: devops-actions/actionlint@ec02b36684b2f574f1d219ad0a43b082e46bf3e4 # v0.1.13
