name: "Lint actions"
description: "Lints GitHub workflow files using actionlint"

inputs:
  version:
    description: "Version of actionlint to use"
    required: false
    default: "latest"
  display-findings: # requires additional setup, see https://github.com/rhysd/actionlint/blob/main/docs/usage.md#problem-matchers for more information
    description: "Whether to display findings in PR UI or not"
    required: false
    default: "true"
  problem-matcher-path:
    description: "Path to the problem matcher configuration file when using display-findings: true"
    required: false
    default: ".github/problem-matcher.json"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Download actionlint
      id: get_actionlint
      env:
        DISPLAY_FINDINGS: ${{ inputs.display-findings }}
        PROBLEM_MATCHER_PATH: ${{ inputs.problem-matcher-path }}
        VERSION: ${{ inputs.version }}
      run: |
        if [[ "$DISPLAY_FINDINGS" == "true" ]]; then
          echo "::add-matcher::$PROBLEM_MATCHER_PATH"
        fi
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) $VERSION
      shell: bash
    - name: Check GitHub action files
      env:
        ACTION_LINT_EXECUTABLE: ${{ steps.get_actionlint.outputs.executable }}
      run: $ACTION_LINT_EXECUTABLE -color
      shell: bash
