name: "Lint actions"
description: "Lints GitHub workflow files using actionlint"

inputs:
  version:
    description: "Version of actionlint to use"
    required: false
    default: "latest"
  display-findings: # requires additional setup, see https://github.com/rhysd/actionlint/blob/main/docs/usage.md#problem-matchers for more information
    description: "Whether to display findings in PR UI or not"
    required: false
    default: "true"
  problem-matcher-path:
    description: "Path to the problem matcher configuration file when using display-findings: true"
    required: false
    default: ".github/problem-matcher.json"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Download actionlint
      id: get_actionlint
      run: |
        if [[ "${{ inputs.display-findings }}" == "true" ]]; then
          echo "::add-matcher::${{ inputs.problem-matcher-path }}"
        fi
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) ${{ inputs.version }}
      shell: bash
    - name: Check GitHub action files
      run: ${{ steps.get_actionlint.outputs.executable }} -color
      shell: bash
