name: test-action-dockercompose-healthcheck-stack

services:
  permanent:
    image: alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    command: ["sh", "-c", "while true; do sleep 10; done"]
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 2s

  exiting:
    image: alpine:3.24.1@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    command: ["sh", "-c", "echo 'Exiting service started'; exit 0"]
    depends_on:
      permanent:
        condition: service_healthy