# Workflow to test Action action-maven-build
name: Test action action-maven-build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  test-action-maven-build:
    name: test-action-maven-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-maven-build
        with:
          app-path: __tests__/maven-helloworld
