# Workflow for running security scan using Trivy
name: Test action action-trivy

on:
  push:
    paths:
      - .github/workflows/test-trivy.yml
      - action-templates/actions/action-trivy/action.yml
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  test-trivy:
    if: (github.event_name == 'push' || github.event_name == 'pull_request' || github.event.review.state == 'approved')
    name: test-trivy
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF results to the GitHub Security tab
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-trivy
