# Workflow to test Action action-maven-build
name: Test action action-maven-build
on:
  push:
    paths:
      - .github/workflows/test-action-maven-build.yml
      - action-templates/actions/action-maven-build/action.yml
      - __tests__/maven-helloworld/**
  pull_request:
    types:
      - opened
      - reopened
  pull_request_review:
    types:
      - submitted

permissions:
  contents: read # for checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action-maven-build:
    if: (github.event_name == 'push' || github.event_name == 'pull_request' || github.event.review.state == 'approved')
    name: test-action-maven-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-maven-build
        with:
          app-path: __tests__/maven-helloworld
          java-version: "21"
