name: Test action action-dockercompose-healthcheck
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  test-dockercompose-healthcheck:
    name: test-dockercompose-healthcheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: dockercompose-healthcheck
        uses: ./action-templates/actions/action-dockercompose-healthcheck
        with:
          compose-file-path: "__tests__"
