# Workflow to Test action action-filter
name: Test action action-filter

on:
  push:
     paths:
       - .github/workflows/test-action-filter.yml
       - action-templates/action-filter/action.yml
  pull_request:

permissions:
  contents: read # for checkout

jobs:
  test-action-filter:
    name: test-action-filter
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 2
      - name: test-action-filter
        uses: ./action-templates/actions/action-filter
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            java:
              - '**/*.java'
            javascript-typescript-vue:
              - '**/*.vue'
            actions:
              - '.github/**/*.yml'
              - '.github/**/*.yaml'
              - 'action-templates/**/*.yml'
              - 'action-templates/**/*.yaml'
      - name: echo-output
        env:
          CATEGORIES: ${{ steps.filter.outputs.changes }}
        run: |
          echo "$CATEGORIES"
          # Activate globstar for pattern match
          shopt -s globstar
          
          # list of categories
          # categories=("action" "java" "javascript")
          num_categories=${#CATEGORIES[@]}
          echo "num_categories: $num_categories"
          
          action_found=0
          java_found=0
          javascript_found=0
  
          # get all changed files
          if git rev-parse --verify HEAD~1 > /dev/null 2>&1; then
            echo "git diff HEAD~1"
            git diff HEAD~1..HEAD --no-renames --name-status -z > diff_output.txt
            echo "2"
          else
            # no previous commit, e.g. initial commit
            echo "git diff --root"
            git diff --root --name-status -z > diff_output.txt
            echo "3"
          fi
  
          echo "4"

          while IFS= read -r -d '' line; do
            status="${line:0:1}"
            filename="${line:1}"
            echo "status: $status"
            echo "filename: $filename"
          
            # Check, whether filename follows a category
            for category in "${CATEGORIES[@]}"; do
              echo "category: $category"
          
              case "$category" in
                "[\"actions\"]")
                  echo "category: actions"
                  if [[ $action_found == 0 ]] &&
                   ( [[ "$filename" == .github/**/*.yml ]] || \
                   [[ "$filename" == .github/**/*.yaml ]] || \
                   [[ "$filename" == action-templates/**/*.yml ]] || \
                   [[ "$filename" == action-templates/**/*.yaml ]] ); then
                     num_categories=$((--num_categories))
                     action_found=1
                     break
                   fi
                   ;;
                "java")
                  echo "category java"
                  if [[ $java_found == 0 ]] && [[ "$filename" == **/*.java ]]; then
                     num_categories=$((num_categories - 1))
                     java_found=1
                     break
                   fi
                   ;;
                "javascript")
                  if  [[ $javascript_found == 0 ]] && [[ "$filename" == **/*.vue ]]; then
                    echo "category javascript"
                    num_categories=$((num_categories - 1))
                    javascript_found=1
                    break
                  fi
                  ;;
                *)
                  # File has not category
                  echo "no category for this file"
                  ;;
              esac
            done
          done < diff_output.txt
          
          echo "5"
          if [[ $num_categories > 0 ]]; then
            echo "num_categories: $num_categories"
            exit 1
          fi
          
          echo "Filter action ok"
