# Workflow to test action action-actionlint.yml
name: Test action action-actionlint
on:
  push:
    paths:
      - .github/workflows/test-action-actionlint.yml
      - .github/action-templates/actions/action-actionlint/action.yml
  pull_request:
    types:
      - opened
      - reopened
  pull_request_review:
    types:
      - submitted

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

# minimal test that action-actionlint is running as the implementation should change (see https://github.com/it-at-m/lhm_actions/issues/275)
jobs:
  test-actionlint-with-default-settings:
    if: github.event.review.state == 'approved' # run only if pull-request is approved
    name: test-actionlint-with-default-settings
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@6db6885319cb1f85f75cd2947caa96596047711b
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: test-actionlint-with-default-settings
        uses: ./action-templates/actions/action-actionlint
