name: Test action-npm-release

on:
  workflow_dispatch:

env:
  app-path: "docs"
  use-pr: true
  release-version: "patch"

permissions:
  contents: read # for checkout

jobs:
  test-npm-release:
    name: test-npm-release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: npm-release
        uses: ./action-templates/actions/action-npm-release
        with:
          app-path: ${{ env.app-path }}
          releaseVersion: ${{ env.release-version }}
          use-pr: ${{ env.use-pr }}
