# Workflow to test Action action-maven-build
name: Test action action-maven-build
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # for checkout

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-action-maven-build:
    name: test-action-maven-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-maven-build
        with:
          app-path: __tests__/maven-helloworld
          java-version: "21"
