# Workflow for running security scan using Trivy
name: Test action action-trivy

on:
  push:
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required to upload SARIF results to the GitHub Security tab
    steps:
      - uses: ./action-templates/actions/action-trivy
