# Workflow to checkout repository
name: Test action action-actionlint

on:
  push:
    branches:
      - main
      - 185-test-workflows-for-lhm_actions
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # for checkout

# minimal test that action-actionlint is running as the implementation should change (see https://github.com/it-at-m/lhm_actions/issues/275)
jobs:
  test-actionlint-with-default-settings:
    name: test-actionlint-with-default-settings
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: test-actionlint-with-default-settings
        uses: ./action-templates/actions/action-actionlint

  test-actionlint-with-display-findings-false:
    name: test-actionlint-with-display-findings-false
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: test-actionlint-with-display-findings-false
        uses: ./action-templates/actions/action-actionlint
        with:
          display-findings: false
