# Workflow to checkout repository
name: Test action action-checkout

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  test-checkout-persist-credentials-default:
    name: test-persist-credentials-default
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-checkout
      - name: persist-credentials-default
        run: ls $RUNNER_TEMP

  test-checkout-persist-credentials-false:
    name: test-persist-credentials-false
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-checkout
        with:
          persist-credentials: false
      - name: persist-credentials-false
        run: ls $RUNNER_TEMP

  test-checkout-persist-credentials-true:
    name: test-persist-credentials-true
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./action-templates/actions/action-checkout
        with:
          persist-credentials: true
      - name: persist-credentials-true
        run: ls $RUNNER_TEMP
