name: Test action-create-github-release

on:
  push:
    paths:
      - .github/workflows/test-action-github-release.yml
      - action-templates/actions/action-create-github-release/action.yml
  pull_request:
    types:
      - opened
      - reopened
  pull_request_review:
    types:
      - submitted

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write # must be removed if use-pr is 'false'
jobs:
  test-create-release:
    if: (github.event_name == 'push' || github.event_name == 'pull_request' || github.event.review.state == 'approved')
    name: test-npm-build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-local-actions
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/upload-artifact@v7
        with:
          path: action-templates/actions
      - name: create-release
        uses: ./action-templates/actions/action-create-github-release
        with:
          artifact-name: artifact
          artifact-path: artifact.zip
          skip-artifact-decompress: true
          tag-name: test-test
      - name: script
        run: |
          mkdir testfolder
          cd testfolder
          gh release download test-test
          unzip artifact.zip
          output=$(ls action-create-github-release)
          echo $output
          if [ "$output" != "action.yml" ]; then
            echo "Stimmt nicht überein!"
            exit 1
          fi
          gh release delete test-test --cleanup-tag
